import React, { useState, useEffect } from 'react';
import api from '../services/api';
import './Receipt.css';

export default function ZReportReceipt({ shift }) {
  const [settings, setSettings] = useState(null);

  useEffect(() => {
    api.get('/settings').then(res => setSettings(res.data.data)).catch(console.error);
  }, []);

  if (!shift) return null;

  const openDate = new Date(shift.openedAt);
  const closeDate = new Date();
  
  const formatDate = (d) => d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const formatTime = (d) => d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="receipt-container">
      {/* Header */}
      <div className="receipt-header">
        <div className="receipt-header-left">
          <img src="/receipt-logo.jpg" alt="Apna Mart" className="receipt-logo" />
        </div>
        <div className="receipt-header-right">
          <h1 className="receipt-store-name">{settings?.storeName || 'Apna Mart'}</h1>
          <p className="receipt-address">{settings?.storeAddress || 'Gaya Bhagat Chowk, Golma, District - Saharsa, PIN-852107'}</p>
        </div>
      </div>

      <div className="receipt-separator" />
      <h2 style={{ textAlign: 'center', margin: '5px 0', textTransform: 'uppercase' }}>END OF DAY (Z-REPORT)</h2>
      <div className="receipt-separator" />

      {/* Shift Information */}
      <div className="receipt-info">
        <div className="receipt-info-row">
          <span className="receipt-info-label">Shift ID</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">{shift.id.split('-')[0].toUpperCase()}</span>
        </div>
        <div className="receipt-info-row">
          <span className="receipt-info-label">Opened</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">{formatDate(openDate)} {formatTime(openDate)}</span>
        </div>
        <div className="receipt-info-row">
          <span className="receipt-info-label">Closed</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">{formatDate(closeDate)} {formatTime(closeDate)}</span>
        </div>
      </div>

      <div className="receipt-separator" />

      {/* Financials Section */}
      <div className="receipt-payment">
        <div className="receipt-pay-row">
          <span className="receipt-info-label">Opening Float</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">Rs. {parseFloat(shift.openingFloat).toFixed(2)}</span>
        </div>
        <div className="receipt-pay-row">
          <span className="receipt-info-label">Cash Sales</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">Rs. {parseFloat(shift.totalSalesCash).toFixed(2)}</span>
        </div>
        <div className="receipt-pay-row">
          <span className="receipt-info-label">UPI Sales</span>
          <span className="receipt-info-colon">:</span>
          <span className="receipt-info-value">Rs. {parseFloat(shift.totalSalesUPI).toFixed(2)}</span>
        </div>
      </div>

      <div className="receipt-separator" />

      {/* Cash Drawer Section */}
      <div className="receipt-totals">
        <div className="receipt-total-row">
          <span>Expected Cash in Drawer</span>
          <span>Rs. {parseFloat(shift.expectedCash).toFixed(2)}</span>
        </div>
        <div className="receipt-total-row" style={{ fontWeight: 'bold' }}>
          <span>Actual Counted Cash</span>
          <span>Rs. {parseFloat(shift.actualCash).toFixed(2)}</span>
        </div>
        <div className="receipt-total-row receipt-final-total" style={{ color: parseFloat(shift.actualCash) - parseFloat(shift.expectedCash) < 0 ? 'red' : 'inherit' }}>
          <span>DIFFERENCE</span>
          <span>Rs. {(parseFloat(shift.actualCash) - parseFloat(shift.expectedCash)).toFixed(2)}</span>
        </div>
      </div>

      <div className="receipt-separator" />

      {/* Footer */}
      <div className="receipt-footer">
        <p>Shift Closed Successfully</p>
        <p style={{ marginTop: '10px', fontSize: '10px' }}>Generated by Apna Mart POS System</p>
      </div>
    </div>
  );
}
